version: 2
jobs:
  build: 
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "installing packages"
      - run: yarn install
      - run: CI=true yarn build
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Testing app..."
      - run: yarn install
      - run: yarn test --passWithNoTests
  echotest:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "will test the app now..."
workflows:
  version: 2
  build_test_lint:
    jobs:
      - build
      - echotest
      - test:
        requires:
          - echotest